config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :years

   root 'welcome#index'

end

app/models/discription.rb
class Discription < ActiveRecord::Base
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/poi.rb
class Poi < ActiveRecord::Base
end

app/models/year.rb
class Year < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @years = Year.all

  end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rpersonalsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#top">J.S.</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#2012">2012 <span class="sr-only">(current)</span></a></li>
        <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#2014">2014</a></li>
        <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#2015">2015</a></li>
        <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#Recently">Present</a></li>
        <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#contact">Contact</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="row" ng-attr-id="top" style="margin-bottom: 20px; margin-top: 50px; padding-bottom:60px; border-bottom: solid rgb(247, 180, 180) 3px">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="row" style="margin-bottom:30px;">
      <div class="col-md-12"><img style="max-width:300px; padding-top: 40px;"src="images/Circle_Picture.png"></div>
    </div>
    <div class="row" >
      <div class="col-md-2"></div>
      <div class="col-md-4"><a href="images/resume.pdf" target="_blank"><div class="main-item">RESUME</div></a></div>
      <div class="col-md-4"><a href="images/transcript.pdf" target="_blank"><div class="main-item">TRANSCRIPT</div></a></div>
      <div class="col-md-2"></div>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>






<% @years.each do |year| %>
<div class="year">
  <h1 id="<%= year.year %>"><%= year.year %></h1>
  <div class="language-header">

    Languages Known:
  </div>
  <%languages = Language.where(yeartitle:year.year) %>
  <% languages.each do |lan| %>
  <span class="bolder"><%= lan.text.html_safe %></span>
  <% end %>
  <div class="row">
    <%pois = Poi.where(yeartitle:year.year) %>
    <% pois.each do |poi| %>
        <div class="center col-md-<%= 12/pois.length %>">
          <h3><%=poi.title.html_safe%> </h3>
          <div>
            <p>
              <%=poi.addition.html_safe%>
            </p>
          </div>

          <%discriptions = Discription.where(poititle:poi.title) %>
          <% discriptions.each do |desc| %>
              <div>
                <p>
                  <%=desc.text.html_safe%>
                </p>
              </div>
          <% end %>
        </div>
    <% end %>
  </div>

</div>
<% end %>









<div class="contact-me">
  <h1 id="contact">Contact</h1>
  <div class="row">
    <div class="col-md-3"><h3 class="email"><a href="https://www.facebook.com/jackson.stone.3720" target="_blank">Facebook</a></h3></div>
    <div class="col-md-3"><h3 class="email"><a href="https://twitter.com/CpuStone" target="_blank">Twitter</a></h3></div>
    <div class="col-md-3"><h3 class="email"><a href="https://www.linkedin.com/in/jastone2" target="_blank">Linkedin</a></h3></div>
    <div class="col-md-3"><h3 class="email"><a href="mailto:jackson@mytorch.com" target="_top">jackson@mytorch.com</a></h3></div>
  </div>
</div>

app/views/years/edit.html.erb
<h1>Editing article</h1>
<%=@year %>

<%= form_for :year, url: year_path(@year), method: :patch do |f| %>

    <% if @year.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@year.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @year.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

<%= link_to 'Back', year_path %>

app/views/years/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @years.each do |year| %>
      <tr>
        <td><%= year.title %></td>
        <td><%= year.text %></td>
        <td><%= link_to 'Show', year_path(year) %></td>
        <td><%= link_to 'Edit', edit_year_path(year) %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'New Year', new_year_path %>
<%= link_to 'Back', '/' %>

app/views/years/new.html.erb
<%= form_for :year, url: years_path do |f| %>
    <% if @year.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@year.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @year.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', years_path %>

app/views/years/show.html.erb
Showing Year

<p>
  <strong>Title:</strong>
  <%= @year.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @year.text %>
</p>

<%= link_to 'Back', years_path %>
<%= link_to 'Edit', edit_year_path(@year) %>